Repository urstrulynishkarsh/ReactChat, pull requests merged in 2024-06, with the labels that each got.

#185 Enhanced chat interface UI
  src/Components/ChatPage.jsx
  src/Components/MessageTemplate.css
  src/Components/MessageTemplate.jsx
Labels: gssoc, level1

#179 Added Greeting bot
  .github/workflows/greetings.yml
Labels: enhancement, gssoc, level1

#187 Send messages on right and receive on left side 🌟
  src/App.css
  src/Components/ChatPage.jsx
  src/Components/LocationTemplate.jsx
  src/Components/MessageTemplate.jsx
Labels: enhancement, gssoc, level2
