Repository urstrulynishkarsh/ReactChat, pull requests merged in 2024-05, with the labels that each got.

#66 icon_added
  public/index.html
Labels: GSSoC'24, Level 1

#83 Added CONTRIBUTING.md
  CONTRIBUTING.md
Labels: gssoc, level1

#137 #127 HOME PAGE UI CHANGES RESPONSIVE
  src/Components/HomePage.css
  src/Components/HomePage.jsx
Labels: gssoc, level1, level2

#144 Added pull_request_template.md
  .github/pull_request_template.md
Labels: gssoc, level1
